project:
  type: book
  output-dir: docs

book:
  title: "Introduction to Survival Analysis"
  subtitle: "Modeling Medical Time-to-Event Data Using R Software Packages"
  author: Kristen Varin
  date: "9/6/2023"
  chapters:
    - index.qmd
    - KaplanMeier.qmd
    - HazardAnalysis.qmd
    - Discussion.qmd

bibliography: references.bib

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
  pdf:
    documentclass: scrreprt
  
editor: visual