project:
  type: book
  output-dir: docs

book:
  title: "Survival Analysis Senior Project"
  author: "Kristen Varin"
  date: "9/6/2023"
  chapters:
    - index.qmd
    - Kaplan_Meier.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

