# Survival Analysis

## Survival Analysis Background
Survival analysis is a type of statistical analysis used for analyzing the relationship between time and an event of interest occurring for individuals. The name survival analysis implies that the most common outcome analyzed is death, but many other events can be analyzed such as time it takes to begin recovery from treatment or time until a disease is contracted. These analyses are specifically helpful when comparing treatment groups, different age groups, or other stratifications of people. Survival analysis can reveal whether certain treatments are more effective than others in helping individuals to live longer or avoid other outcomes of interest, such as heart attacks. 

## Example dataset in R
To demonstrate survival analysis, an example dataset was created including ten observations and a time variable ranging from one to ten. Each observation was either assigned a 1, which represented the event occurrence, or a 0, representing no event occurrence. For those assigned a 1, a survival time was assigned in the range of 1 to 9. For those assigned a 0, a time of 10 was assigned, representing the end of the hypothetical study. To create a survival curve, the following steps need to be taken: finding the probability of survival at each time from 0 to 10 and plotting each point must be plotted on a graph. For the first point, probability of survival is always a 1 because every participant begins the study alive. For the first point in the dataset, the observation was assigned a 1 at time 1. When an individual experiences the outcome of interest, the total probability of survival for the group decreases, which is why survival curves have a rightly skewed distribution. The probability of surviving to time 1 would be the number of participants that did not experience the outcome divided by the total number of participants in the study, which would be nine participants divided by 10 subjects, or 0.9. After calculating the probability for each point in a similar way, the survival curve can be graphed (Figure 1). Summary statistics can also be calculated for these values. 

Table walking through the example probabilities here

## Censoring Background
One issue with survival analysis data is the problem of an individual being lost to follow up, which causes the outcome of interest to not be recorded for some reason, such as them dropping out of the study. When this happens, the survival times for those individuals must be censored, causing standard analysis techniques to be inappropriate for these data. There are three types of censoring that can occur. The first type of censoring is called right censoring, because the censored survival time for these individuals is equal to the total time they were known to be alive in the study after time t0, the beginning of the observation period, before they were lost-to-follow-up. This happens in instances such as when an individual dies due to a non-related event after the study begins. In left censoring, the individual experiences lost-to-follow-up before the observation period begins. This would happen, for example, when a study aimed to track progress from a treatment a month after the treatment began, but the patient died less than a month after beginning treatment. Finally, interval censoring happens when the patient comes in and out of the study, making it possible for them to experience the outcome of interest during a period of time when they aren’t being observed. This, along with left censoring, often happens when recurrence is being tracked in a study. One example could be if recurrence of cancer is being tracked and the study checks in with patients every month. If an individual does not have cancer after the first month but then does after the second month, the recurrence time is somewhere between one and two months, and it therefore needs to be interval censored (Collet 2). 





