# Kaplan Meier

## Kaplan Meier Curve
The Kaplan Meier curve is a graphical representation of survival analysis. Similar to the survival curve discussed previously, the Kaplan Meier curve shows the relationships between time, which is typically plotted on the x-axis, and probability of survival, which is typically on the y-axis. The biggest difference between the two curves is that the Kaplan Meier curve factors in right censoring by eliminating individuals after their censored time is reached from the total number of participants. Probability of survival at a given time is calculated with the following expression where $S(t_j)$ is the probability of being alive at time tj, S(tj-1) is the probability of being alive at tj-1, nj is the number of patients alive just before tj, dj is the number of events at tj, and j is the time interval of interest: S(tj) = S(tj-1)(1-djnj) (Clark et al). The function essentially divides the surviving individuals by the individuals at risk, similar to the previous calculations shown. However, the main difference of Kaplan Meier curves compared to other probability techniques is that the number of individuals at risk, nj, does not include those who have been censored at that time. This adjustment prevents overestimating the survival probability because it no longer assumes censored individuals are still alive or and at risk (Goel et al). 

Add in: 
- A 95% confidence interval for each point can be found by 
- Median / finding probability at a certain time? 

## Kaplan Meier in R
Luckily, modern software makes these calculations easy and fast, as well as plotting them with confidence intervals and risk tables. The survival package in R has a function called Surv() that takes input data and creates a response object recording survival time for each observation. This object can then be used for the response in the regression functionSurvfit2() in the ggsurvfit package, which plots the Kaplan Meier curve for the data. The function takes into account right censoring as well, marking censored times with a + symbol in the object created and then editing the regression accordingly (Zabor, E). The code for Figure 2 looks as follows: 


